# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-16 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='sales',
            field=models.IntegerField(default=10, verbose_name='商品销量'),
        ),
    ]
