# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190216_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='books', verbose_name='商品图片'),
        ),
    ]
